version: "3.8"

services:
  whoami:
    image: traefik/whoami
    hostname: "anw-{{.Node.Hostname}}-{{.Service.Name}}-{{.Task.Slot}}"
    deploy:
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`who.israel.com.br`)
        - traefik.http.routers.whoami.entrypoints=websecure
        - traefik.http.routers.whoami.tls.certresolver=le
        - traefik.http.routers.whoami.service=whoami
        - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - traefik_public

    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik_public:
    external: true